version: '3.8'

services:
  hajimi-king-pro:
    image: ghcr.io/hyb-oyqq/hajimi-king-pro:dev-08781bb
    container_name: hajimi-king-pro
    restart: unless-stopped
    network_mode: host
    # 环境变量
    env_file:
      - .env
    
    # 数据卷挂载
    volumes:
      - ./data:/app/data